### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by edwincara** [toondaey/nestjs-pdf#10]
Hi,

I got this error 

 Parameter 'pdf' of constructor from exported class has or is using private name 'PDF'.

**Comment by toondaey** [comment]
@edwincara This is a pretty vague error, could you provide code snippet(s) for this?

**Comment by edwincara** [comment]
@toondaey Hi B'Tunde,

Here is my pdf module and service code if that help, i followed your instruction since im newbie to nestjs i dont know if i did something wrong.  

Service Comp.

`import { Model } from 'mongoose';
import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Pdf } from './schemas/pdf.schema';
import { CreatePdfDto } from './dto/create-pdf.dto';

@Injectable()
export class PdfsService {
  constructor(@InjectPdf() pdf: PDF, @InjectModel(Pdf.name) private PdfsModel: Model<Pdf>) {}

  async create() {
    return this.pdf({
        filename: './filename.pdf', // where pdf will be generated. Generally comprises of the path and filename
        template: 'templateName',
    }); // This will generate the pdf file at process.cwd() + './filename.pdf'.
}

  async findAll(UpdateAgencyDto): Promise<Pdf[]> {
    return this.PdfsModel.find(UpdateAgencyDto).exec();
  }
  async findOne(id): Promise<Pdf[]> {
    return this.PdfsModel.find({_id:id}).exec();
  } 
 
  async findOneAndDelete(id): Promise<Pdf> {
    return this.PdfsModel.findOneAndDelete({ _id: id });
  }
}

`

PDF Module

`import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { PdfsController } from './pdfs.controller';
import { PdfsService } from './pdfs.service';
import { Pdf, PdfSchmea } from './schemas/pdf.schema';
import { PdfConfigService } from './pdf-config.service';
import { PDFModule, PDFModuleOptions, } from 'nestjs-pdf';

@Module({
  imports: [
    PDFModule.register({
      view: {
          root: '/path/to/template',
          engine: 'pug',
      },
  }),
    MongooseModule.forFeature([{ name: Pdf.name, schema: PdfSchmea }]),
  
  ],
  controllers: [PdfsController],
  providers: [PdfsService],
})
export class PdfsModule {}`

**Comment by toondaey** [comment]
Oh, sorry for the wrongful documentation. Can you change
```ts
constructor(@InjectPdf() pdf: PDF, @InjectModel(Pdf.name) private PdfsModel: Model) {}
```
to
```ts
constructor(@InjectPdf() private pdf: PDF, @InjectModel(Pdf.name) private PdfsModel: Model) {}
```
?

This should work.
