### ISSUE TITLE
PDFService not found 

### ISSUE THREAD

**Issue by UjjualUSspericorn** [toondaey/nestjs-pdf#30]
I was following the documentation and creating an injectable class but PDFService is not found.

import { PDFService } from 'nestjs-pdf';
import { Injectable } from '@nestjs/common';

@Injectable()
export class YourService {
    constructor(private readonly pdfService: PDFService);

    generatePDFToFile(
        template: string,
        filename?: string,
        options: PDFOptions,
    ) {
        this.pdf.toFile(template, filename, options); // returns Observable<FileInfo>;
    }

    generatePDFToStream(template: string, options?: PDFOptions) {
        this.pdf.toStream(template, options); // returns Observable<Readable>;
    }

    generatePDFToBuffer(template: string, options?: PDFOptions) {
        this.pdf.toBuffer(template, options); // returns Observable<Buffer>;
    }
}

---eslint error hint----
import PDFService

Module '"../../../node_modules/nestjs-pdf"' has no exported member 'PDFService'.

I am I missing something ?

**Comment by toondaey** [comment]
Sorry about that, the documentation is wrong. It should have been `import { PDFService } from '@t00nday/nestjs-pdf'`

**Comment by toondaey** [comment]
Sorry about that, the documentation is wrong. It should have been `import { PDFService } from '@t00nday/nestjs-pdf'`
