### ISSUE TITLE
Cannot find module '@t00nday/nestjs-pdf' or its corresponding type declarations.

### ISSUE THREAD

**Issue by UjjualUSspericorn** [toondaey/nestjs-pdf#39]
Hi,

@t00nday/nestjs-pdf is not recognising in the nest-js library.

below given is the error . any idea on this ?

src/config/pdf/Pdf.service.ts:1:28 - error TS2307: Cannot find module '@t00nday/nestjs-pdf' or its corresponding type declarations.

 import { PDFService } from '@t00nday/nestjs-pdf';

**Comment by toondaey** [comment]
Hi @UjjualUSspericorn , have you been able to solve this?

**Comment by sakadoddle** [comment]
@UjjualUSspericorn  How did you solve this issue ?
