### ISSUE TITLE
Please make sure that the argument PdfToken(default) at index [5] is available in the AppModule context...

### ISSUE THREAD

**Issue by ecorona** [toondaey/nestjs-pdf#4]
Hi there! im trying to implement your library by following your instructions but i'm getting this error:

```bash
[Nest] 21182   - 06/19/2020, 11:24:57 PM   [ExceptionHandler] Nest can't resolve dependencies of the AppService (ProfilesService, UsersService, MyLogger, RulesService, ConfigService, ?). Please make sure that the argument PdfToken(default) at index [5] is available in the AppModule context.

Potential solutions:
- If PdfToken(default) is a provider, is it part of the current AppModule?
- If PdfToken(default) is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing PdfToken(default) */ ]
  })
```

Is there anything missing on the exports/imports side?

thank you

**Comment by ecorona** [comment]
Update:

this only happens when using:
```typescript
    PDFModule.registerAsync({
      useFactory: (): PDFModuleOptions => ({
        view: {
          root: './templates',
          engine: 'ejs',
        },
      }),
    }),
```
It works fine when using: 
```typescript
    PDFModule.register({
      view: {
        root: './templates',
        engine: 'ejs',
      },
    }),
```

**Comment by toondaey** [comment]
Hi @ecorona, apologies for the late response.
This bug has been fixed by #5 . Please update to version 1.0.4 of the package.

**Comment by hdiaz-nectia** [comment]
Hi, I am using the latest version "^1.0.4", and  I'm getting the same error describe above:

[```
NestWinston] Error     2020-11-12 12:28:34 [ExceptionHandler] Nest can't resolve dependencies of the PdfService (?). Please make sure that the argument PdfToken(a) at index [0] is available in the MyAppModule context.

Potential solutions:
- If PdfToken(a) is a provider, is it part of the current MyAppModule?
- If PdfToken(a) is exported from a separate @Module, is that module imported within MyAppModule?
  @Module({
    imports: [ /* the Module containing PdfToken(a) */ ]
  })
```

**Comment by hdiaz-nectia** [comment]
**AppModule**

```
...
    PDFModule.register({
      view: {
        root: '/commons/template',
        engine: 'pug',
      },
    }),
...
export class AppModule {

  static port: number | string;

  constructor(private readonly _configService: AppConfigService) {
    AppModule.port = _configService.get(Configuration.PORT);
  }
}

```

**LiquidacionesModule**

```
@Module({
    imports: [
        MongooseModule.forFeature([
            { name: Liquidacion.name, schema: LiquidacionSchema },
            { name: Hes.name, schema: HesSchema },
        ])
    ],
    controllers: [LiquidacionesController],
    providers: [LiquidacionesService, HesService, ReportService, PdfService, Logger],
    exports: [LiquidacionesService]
})
export class LiquidacionesModule {}
```

**Comment by hdiaz-nectia** [comment]
I move config from AppModule to LiquidacionesModule and it works

**Comment by toondaey** [comment]
I think you just have to make your config module global to get it to work that way.
