### ISSUE TITLE
Creating a stream without file

### ISSUE THREAD

**Issue by pietrzakadrian** [toondaey/nestjs-pdf#8]
I would need the created file to put on my AWS S3 bucket. For that, I would have to do something similar to this:

```
  pdf.create(html, options).toStream(function(err, stream) {
    if (err) return console.log(err)
    uploadToS3(stream, filename)
  });
```

Is it possible to use this package?

**Comment by pietrzakadrian** [comment]
@toondaey ?

**Comment by toondaey** [comment]
I'm sorry for the late response. I'm sorry but this is not built into the package yet. I'll have to look into it.

**Comment by pietrzakadrian** [comment]
Any updates? @toondaey

**Comment by hdiaz-nectia** [comment]
I need the same options in my proyect: toStream (upload aws), toBuffer (to encrypt with password)

**Comment by toondaey** [comment]
I apologize for not addressing this issue early enough.
I will be deploying a v2.0.0 in the next 24 hours that provides these methods as `Observables`.

**Comment by hdiaz-nectia** [comment]
> I apologize for not addressing this issue early enough.
> I will be deploying a v2.0.0 in the next 24 hours that provides these methods as `Observables`.

Also I have an error related with a closed issue #4 PdfToken (I am using the latest version "^1.0.4")

**Comment by toondaey** [comment]
Could you provide a code snippet and specific error you're facing?

**Comment by hdiaz-nectia** [comment]
[NestWinston] Error     2020-11-12 12:57:17 [ExceptionHandler] Nest can't resolve dependencies of the PdfService (?). Please make sure that the argument PdfToken(default) at index [0] is available in the LiquidacionesModule context.

Potential solutions:
- If PdfToken(default) is a provider, is it part of the current LiquidacionesModule?
- If PdfToken(default) is exported from a separate @Module, is that module imported within LiquidacionesModule?
  @Module({
    imports: [ /* the Module containing PdfToken(default) */ ]
  })


> Could you provide a code snippet and specific error you're facing?

This happens with PDFModule.register and PDFModule.registerAsync

```
[NestWinston] Error     2020-11-12 12:57:17 [ExceptionHandler] Nest can't resolve dependencies of the PdfService (?). Please make sure that the argument PdfToken(default) at index [0] is available in the LiquidacionesModule context.

Potential solutions:
- If PdfToken(default) is a provider, is it part of the current LiquidacionesModule?
- If PdfToken(default) is exported from a separate @Module, is that module imported within LiquidacionesModule?
  @Module({
    imports: [ /* the Module containing PdfToken(default) */ ]
  })
```

**Comment by toondaey** [comment]
Can you share your snippets of your `LiquidacionesModule` please?

**Comment by hdiaz-nectia** [comment]
> Can you share your snippets of your `LiquidacionesModule` please?

Sorry, I shared my code in the issue #4#issuecomment-726208229

**Comment by hdiaz-nectia** [comment]
Is it posible encrypt with password a buffer pdf ?

**Comment by toondaey** [comment]
Unfortunately, at this moment, that's not possible.

**Comment by toondaey** [comment]
A deployment for version 2 is now available @ `@t00nday/nestjs-pdf` supporting this feature request.
